services:
  # ----------------------------------------------------
  # Web Application & Telegram Bot Webhook Service
  # ----------------------------------------------------
  - type: web
    name: inventory-web
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: singapore
    envVars:
      - key: PORT
        value: "80"
      - key: DB_DRIVER
        value: "pgsql"
      - key: DB_HOST
        value: "aws-0-ap-northeast-2.pooler.supabase.com"
      - key: DB_USER
        value: "postgres.wpzaeloeqsiacehkxvgq"
      - key: DB_PASS
        value: "Monyvann310394"
      - key: DB_NAME
        value: "postgres"
      - key: DB_PORT
        value: "6543"
