-- ============================================================
-- SUPABASE / POSTGRESQL SCHEMA FOR INVENTORY MANAGEMENT SYSTEM
-- Copy and paste this script into your Supabase SQL Editor
-- ============================================================

-- 1. Automatic Timestamp Update Triggers
CREATE OR REPLACE FUNCTION update_lastupdate_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.lastupdate = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ language 'plpgsql';

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.updated_at = CURRENT_TIMESTAMP;
   RETURN NEW;
END;
$$ language 'plpgsql';

-- ------------------------------------------------------------
-- TABLE: users
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'user',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: category
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    category_code VARCHAR(50) NOT NULL,
    category_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastupdate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_cat_code UNIQUE (user_id, category_code),
    CONSTRAINT uq_user_cat_name UNIQUE (user_id, category_name)
);

CREATE INDEX IF NOT EXISTS idx_category_user_id ON category(user_id);

DROP TRIGGER IF EXISTS trg_category_lastupdate ON category;
CREATE TRIGGER trg_category_lastupdate
BEFORE UPDATE ON category
FOR EACH ROW EXECUTE FUNCTION update_lastupdate_column();

-- ------------------------------------------------------------
-- TABLE: product
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    product_code VARCHAR(50) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    category_id BIGINT NOT NULL REFERENCES category(id) ON DELETE CASCADE,
    price NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    quantity INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastupdate TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_prod_code UNIQUE (user_id, product_code)
);

CREATE INDEX IF NOT EXISTS idx_product_user_id ON product(user_id);
CREATE INDEX IF NOT EXISTS idx_product_category_id ON product(category_id);

DROP TRIGGER IF EXISTS trg_product_lastupdate ON product;
CREATE TRIGGER trg_product_lastupdate
BEFORE UPDATE ON product
FOR EACH ROW EXECUTE FUNCTION update_lastupdate_column();

-- ------------------------------------------------------------
-- TABLE: user_telegram_bots
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS user_telegram_bots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE,
    bot_token VARCHAR(255) NOT NULL,
    bot_username VARCHAR(100) NOT NULL,
    chat_id VARCHAR(100) DEFAULT NULL,
    connection_code VARCHAR(50) DEFAULT NULL,
    code_expires_at TIMESTAMPTZ DEFAULT NULL,
    connected_at TIMESTAMPTZ DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: system_settings
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_settings (
    setting_key VARCHAR(50) PRIMARY KEY,
    setting_value VARCHAR(255) NOT NULL
);

INSERT INTO system_settings (setting_key, setting_value) 
VALUES ('auto_telegram_notify', '1')
ON CONFLICT (setting_key) DO NOTHING;

-- ------------------------------------------------------------
-- TABLE: telegram_subscribers
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telegram_subscribers (
    chat_id VARCHAR(100) PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: grid_state
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS grid_state (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grid_name VARCHAR(100) NOT NULL UNIQUE,
    state_json TEXT DEFAULT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS trg_grid_state_updated_at ON grid_state;
CREATE TRIGGER trg_grid_state_updated_at
BEFORE UPDATE ON grid_state
FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ------------------------------------------------------------
-- TABLE: processed_telegram_updates
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS processed_telegram_updates (
    update_id BIGINT PRIMARY KEY,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- TABLE: telegram_push_logs
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telegram_push_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    chat_id VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    status VARCHAR(50) NOT NULL,
    error_message TEXT DEFAULT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
